ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Copy the prom.yml configuration file to the container
COPY prom.yml /etc/prometheus/prom.yml
COPY entrypoint.sh /entrypoint.sh

# Command to run Prometheus
ENTRYPOINT ["/entrypoint.sh"]
